Repository jwplayer/hls.js, pull requests merged in 2018-10, with the labels that each got.

#176 Use channel number over static field to determine captions channel
  src/utils/cea-608-parser.js
Labels: upstream-this

#178 Avoid inserting 608 characters to a channel which does not match the current field
  src/utils/cea-608-parser.js
Labels: bug

#179 Remove package-lock.json and upgrade to yarn
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement
